### ISSUE TITLE
Bulk loading multiple hits

### ISSUE THREAD

**Issue by andyzeli** [dbarowy/AutoMan#31]
just wanted to ask one more question. can close this issue (its not an issue) but just wanted to get your thoughts. 

The Java SDK includes the createHITs plural option and the Velocity templating library for bulk creating HITs from data files. The Site Category example illustrates its use.

If Im reading correctly: The Automan library implements the smart crowdsourcing logic of your research. All of the handling is for a single question, though it does create threads. Multiple questions are handled client side, as in the anpr example - mapping the list of data items to the Question factory function.

If in the end, the goal is to crowd source 10 thousand or 100 thousand like questions, is this still an ok approach? perhaps implementing a stream with backpressure on the client side? 

Thanks for your any input!

**Comment by dbarowy** [comment]
Hi @andyzeli, if I read your question correctly, you're really asking two things:

1. Is it hard to do multiple HITs with AutoMan?
2. Is AutoMan's mechanism to handle multiple HITs the right one?

OK, so for the first question, my personal feeling is that the answer is no.  When you create a function in AutoMan, you should think of this as analgous to a template.  Admittedly, the actual amount of control I give you over rendered HTML on the MTurk side is not great, but this is something we've discussed (i.e., switch to `HTMLQuestion` and use either Scala XML literals or maybe import a templating lib).  Anyway, to reuse your AutoMan 'template', just call the function again with different arguments.

With regard to the second question, the `createHITs` call in the Java SDK doesn't actually do anything more efficient than AutoMan.  In fact, the MTurk API has no such bulk loading facility.  The SDK's strategy--to make the client do all the heavy lifting using a thread pool--is exactly the same strategy that AutoMan uses.  Have a look at the definition for `createHITs` on line 1423 in the `RequesterService.java` file.

I suspect your real concern is: is the one-thread-per-question strategy a good one?  Will that many threads kill my program?  Will it hammer MTurk?  The answers are no and no.  AFAIK, Java's thread limit really just depends on how much space you have on the heap to allocate thread objects.  AutoMan's scheduler is fairly smart about trying to maximize throughput while not hammering MTurk (all communication with MTurk in fact goes through a single thread that tries to maintain something like the "backpressure" you allude to).  There may be scalability scenarios that I don't handle well, but I have not encountered them in practice; I have personally scaled the current system to well over a thousand concurrent questions (modulo issue #30, which is a recent issue), so I don't think that the basic design is a problem.

The principle that AutoMan tries to enforce is to put work on MTurk as quickly as possible.  The reason is that "human latency" is large compared to typical computer programs, so as soon as we have enough information to schedule the work, do so.  Futures are merely the mechanism used to perform this work asynchronously in a way that I don't find ugly; i.e., users don't need to know how to deal with asynchrony at all except that it's good to maximize the amount of work that AutoMan gets all at once.  As soon as the work is scheduled, the thread spawned by the future blocks and consumes no more resources (except memory) until it is woken up by the AutoMan scheduler with a response.  The one issue with this strategy that AutoMan needs to address is when the amount of work that needs to be scheduled is so large that the initial set of tasks time-out before AutoMan gets around to retrieving their responses.  Thus AutoMan balances posting and retrieving tasks.  It [uses a priority queue to manage this](https://github.com/dbarowy/AutoMan/blob/b7ecab013d9d938fcb618be03c9e0187ba8faee8/libautoman/src/main/scala/edu/umass/cs/automan/adapters/mturk/worker/Messages.scala) and the [worker code](https://github.com/dbarowy/AutoMan/blob/b7ecab013d9d938fcb618be03c9e0187ba8faee8/libautoman/src/main/scala/edu/umass/cs/automan/adapters/mturk/worker/WorkerRunnable.scala) (see line 90) picks tasks out of the queue one at a time in a hybrid of priority and FIFO order (the FIFO ordering is for tasks with the same priority, like posting and retrieving).

Does that answer everything?  If not, feel free to reopen this ticket.

**Comment by andyzeli** [comment]
Thanks @dbarowy for the thoughtful response. Your interpretations of my questions were correct and Im happy with the answer! 

As for the templates, I am actually looking at the added benefit of using ExternalQuestion since MTurk allows that with the only difference being the XML for the question in the createHit method (getting answers is same).  Testing is a bit more difficult, but it seems ExternalQuestion can be supported by switching about 5 lines of code using the fold on Option trickery:
in `MTurkQuestion`:

    protected[mturk] def toXML(randomize: Boolean) : scala.xml.Node
    final def toXMLNode(randomize: Boolean) : scala.xml.Node = _ext_webpage_url.fold(toXML(randomize)) { m =>
    <ExternalQuestion xmlns="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2006-07-14/ExternalQuestion.xsd">
    <ExternalURL>{ m }</ExternalURL>
    <FrameHeight>{ _ext_webpage_frame_height }</FrameHeight>
    </ExternalQuestion>
    }

and in `MTurkMethods`:


    val xml = question.asInstanceOf[MTurkQuestion].toXMLNode(//...

So if an external Url is passed into the question constructor, the toXML is bypassed. Perhaps ExternalQuestion isnt a popular enough option/comes with enough problems to add to this library though..
